"""
Synthetic Groove Validator for Holographic Phase Imaging (HPI)
==============================================================

Validates a holographic groove analyzer against synthetic datasets generated by
holographic_synthetic_generator.py
"""

from __future__ import annotations

import argparse
import csv
import importlib
import importlib.util
import json
import logging
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np


LOG = logging.getLogger("holo_groove_validation")


# =============================================================================
# Configuration and schema
# =============================================================================


@dataclass(frozen=True)
class ImagingConfig:
    # Imaging parameters matching the holographic synthetic generator
    xy_um: float = 0.54
    dz_um_per_gray: float = 75.0 / 255.0  # ≈ 0.294 µm/gray
    z0_um: float = -25.0


@dataclass(frozen=True)
class ValidationConfig:
    # Acceptance thresholds for holographic groove validation
    pitch_mape_thresh_pct: float = 3.0
    depth_mape_thresh_pct: float = 5.0
    angle_err_thresh_deg: float = 4.0


@dataclass(frozen=True)
class SyntheticSample:
    # Ground truth for a single synthetic sample
    file_name: str
    file_path: Path
    pitch_um: float
    depth_um: float
    xy_um_per_px: float
    dz_um_per_gray: float
    z0_um: float
    sample_index: int


@dataclass
class VerificationResult:
    # Result of validating one sample
    file_name: str
    sample_index: int
    passed: bool

    pitch_truth_um: float
    depth_truth_um: float
    angle_truth_deg: float

    pitch_meas_um: float
    depth_meas_um: float
    angle_meas_deg: float

    pitch_mape_pct: float
    depth_mape_pct: float
    pitch_abs_err_um: float
    depth_abs_err_um: float
    angle_err_deg: float

    pitch_pass: bool
    depth_pass: bool
    angle_pass: bool

    error: str = ""


# =============================================================================
# I/O helpers
# =============================================================================


def _read_truth_index(truth_csv: Path) -> List[SyntheticSample]:
    # Read the truth_index.csv generated by holographic_synthetic_generator.py
    base_dir = truth_csv.parent
    required = {
        "file",
        "pitch_um",
        "depth_um",
        "xy_um_per_px",
        "dz_um_per_gray",
        "z0_um",
    }

    out: List[SyntheticSample] = []
    with open(truth_csv, "r", newline="", encoding="utf-8") as f:
        r = csv.DictReader(f)
        if r.fieldnames is None:
            raise ValueError("truth_index.csv has no header row.")
        missing = required - set(r.fieldnames)
        if missing:
            raise ValueError(f"truth_index.csv missing columns: {sorted(missing)}")

        for row in r:
            file_name = str(row["file"]).strip()
            if not file_name:
                continue

            out.append(
                SyntheticSample(
                    file_name=file_name,
                    file_path=base_dir / file_name,
                    pitch_um=float(row["pitch_um"]),
                    depth_um=float(row["depth_um"]),
                    xy_um_per_px=float(row["xy_um_per_px"]),
                    dz_um_per_gray=float(row["dz_um_per_gray"]),
                    z0_um=float(row["z0_um"]),
                    sample_index=int(row.get("sample_index", 0)),
                )
            )
    return out


def _write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        with open(path, "w", encoding="utf-8", newline="") as f:
            f.write("note\nno rows\n")
        return
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


# =============================================================================
# Optional GUI
# =============================================================================

try:
    import tkinter as tk
    from tkinter import filedialog, messagebox
except Exception:
    tk = None
    filedialog = None
    messagebox = None


def _tk_root() -> "tk.Tk":
    if tk is None:
        raise RuntimeError("tkinter is not available.")
    root = tk.Tk()
    root.withdraw()
    root.update()
    return root


def _gui_info(title: str, msg: str, *, kind: str = "info") -> None:
    if messagebox is None:
        raise RuntimeError("tkinter messagebox is not available.")
    root = _tk_root()
    try:
        if kind == "error":
            messagebox.showerror(title, msg, parent=root)
        else:
            messagebox.showinfo(title, msg, parent=root)
    finally:
        root.destroy()


def _gui_pick_file(title: str) -> Path:
    if filedialog is None:
        raise RuntimeError("tkinter filedialog is not available.")
    root = _tk_root()
    try:
        p = filedialog.askopenfilename(
            title=title,
            filetypes=[("Python files", "*.py"), ("All files", "*.*")],
            parent=root,
        )
    finally:
        root.destroy()
    if not p:
        raise SystemExit("No file selected")
    return Path(p)


def _gui_pick_dir(title: str) -> Path:
    if filedialog is None:
        raise RuntimeError("tkinter filedialog is not available.")
    root = _tk_root()
    try:
        p = filedialog.askdirectory(title=title, parent=root)
    finally:
        root.destroy()
    if not p:
        raise SystemExit("No folder selected")
    return Path(p)


# =============================================================================
# Analyzer loading
# =============================================================================


def _load_analyzer_module(target: Path) -> Tuple[Any, str]:
    # Load the holographic analyzer module.

    target = target.resolve()

    if target.is_dir():
        analysis_py = target / "analysis.py"
        if not analysis_py.exists():
            raise RuntimeError(f"{target} does not contain analysis.py")

        sys.modules.pop("analysis", None)
        if str(target) not in sys.path:
            sys.path.insert(0, str(target))
        importlib.invalidate_caches()
        try:
            mod = importlib.import_module("analysis")
        except Exception as e:
            raise RuntimeError(
                f"Failed to import analyzer from folder: {target}\n{e}"
            ) from e
        label = f"refactor:{target.name}"

    elif target.is_file() and target.suffix.lower() == ".py":
        spec = importlib.util.spec_from_file_location(
            "groove_analyzer_holo", str(target)
        )
        if spec is None or spec.loader is None:
            raise RuntimeError(f"Cannot import analyzer: {target}")

        sys.modules.pop(spec.name, None)
        mod = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = mod
        try:
            spec.loader.exec_module(mod)
        except Exception as e:
            raise RuntimeError(f"Failed to import analyzer file: {target}\n{e}") from e
        label = f"monolith:{target.name}"

    else:
        raise RuntimeError(
            "Analyzer path must be a .py file or a folder containing analysis.py"
        )

    if hasattr(mod, "analyze_file"):
        return mod, label
    raise RuntimeError("Analyzer must expose analyze_file function.")


def _analyze_one(
    mod: Any,
    sample: SyntheticSample,
    *,
    outdir: Optional[Path],
) -> Tuple[Dict[str, Any], Optional[str]]:
    # Run the analyzer on one sample

    try:
        kwargs = {
            "outdir": outdir,
        }
        if hasattr(mod, "AnalyzerConfig"):
            try:
                kwargs["config"] = mod.AnalyzerConfig(generate_plots=False)
            except Exception:
                pass

        res_obj = mod.analyze_file(
            Path(sample.file_path),
            xy_um=float(sample.xy_um_per_px),
            dz_um_per_gray=float(sample.dz_um_per_gray),
            z0_um=float(sample.z0_um),
            **kwargs,
        )
    except Exception as e:
        return {}, str(e)

    if isinstance(res_obj, dict):
        res = res_obj
    else:
        try:
            res = asdict(res_obj)
        except Exception:
            res = dict(getattr(res_obj, "__dict__", {}))

    # Extract measured values
    res["pitch_meas_um"] = float(res.get("pitch_um", np.nan))
    res["depth_meas_um"] = float(res.get("depth_um", np.nan))
    res["angle_meas_deg"] = float(res.get("fft_angle_deg", np.nan))
    return res, None


# =============================================================================
# Verification logic
# =============================================================================


def _mape_pct(meas: float, truth: float) -> float:
    # Mean Absolute Percentage Error
    if not (np.isfinite(meas) and np.isfinite(truth) and truth != 0):
        return float("nan")
    return float(abs((meas - truth) / truth) * 100.0)


def _angle_error_deg(meas: float, truth: float) -> float:
    # Angle error accounting for 180° periodicity
    if not np.isfinite(meas) or not np.isfinite(truth):
        return float("nan")
    diff = abs(meas - truth) % 180.0
    return float(min(diff, 180.0 - diff))


def _verify_one(
    mod: Any,
    sample: SyntheticSample,
    cfg: ValidationConfig,
    output_root: Path,
    api_version: str,
) -> VerificationResult:
    # Verify one sample against ground truth

    per_out = output_root / sample.file_name.replace(".tif", "")
    per_out.mkdir(parents=True, exist_ok=True)

    res, err = _analyze_one(mod, sample, outdir=per_out, api_version=api_version)

    # Ground truth angle is always 0 for synthetic holographic data (vertical grooves)
    angle_truth = 0.0

    if err is not None:
        return VerificationResult(
            file_name=sample.file_name,
            sample_index=sample.sample_index,
            passed=False,
            pitch_truth_um=sample.pitch_um,
            depth_truth_um=sample.depth_um,
            angle_truth_deg=angle_truth,
            pitch_meas_um=float("nan"),
            depth_meas_um=float("nan"),
            angle_meas_deg=float("nan"),
            pitch_mape_pct=float("nan"),
            depth_mape_pct=float("nan"),
            pitch_abs_err_um=float("nan"),
            depth_abs_err_um=float("nan"),
            angle_err_deg=float("nan"),
            pitch_pass=False,
            depth_pass=False,
            angle_pass=False,
            error=err,
        )

    pitch_meas = float(res.get("pitch_meas_um", np.nan))
    depth_meas = float(res.get("depth_meas_um", np.nan))
    angle_meas = float(res.get("angle_meas_deg", np.nan))

    pitch_mape = _mape_pct(pitch_meas, sample.pitch_um)
    depth_mape = _mape_pct(depth_meas, sample.depth_um)
    angle_err = _angle_error_deg(angle_meas, angle_truth)

    pitch_abs_err = (
        abs(pitch_meas - sample.pitch_um) if np.isfinite(pitch_meas) else float("nan")
    )
    depth_abs_err = (
        abs(depth_meas - sample.depth_um) if np.isfinite(depth_meas) else float("nan")
    )

    # Tolerances: 2 px for pitch, 2 gray levels for depth
    pitch_abs_tol_um = 2.0 * sample.xy_um_per_px
    depth_abs_tol_um = 2.0 * sample.dz_um_per_gray

    pitch_pass = bool(
        np.isfinite(pitch_meas)
        and (
            (np.isfinite(pitch_mape) and pitch_mape <= cfg.pitch_mape_thresh_pct)
            or (np.isfinite(pitch_abs_err) and pitch_abs_err <= pitch_abs_tol_um)
        )
    )
    depth_pass = bool(
        np.isfinite(depth_meas)
        and (
            (np.isfinite(depth_mape) and depth_mape <= cfg.depth_mape_thresh_pct)
            or (np.isfinite(depth_abs_err) and depth_abs_err <= depth_abs_tol_um)
        )
    )
    angle_pass = bool(np.isfinite(angle_err) and angle_err <= cfg.angle_err_thresh_deg)

    passed = bool(pitch_pass and depth_pass and angle_pass)

    return VerificationResult(
        file_name=sample.file_name,
        sample_index=sample.sample_index,
        passed=passed,
        pitch_truth_um=sample.pitch_um,
        depth_truth_um=sample.depth_um,
        angle_truth_deg=angle_truth,
        pitch_meas_um=pitch_meas,
        depth_meas_um=depth_meas,
        angle_meas_deg=angle_meas,
        pitch_mape_pct=pitch_mape,
        depth_mape_pct=depth_mape,
        pitch_abs_err_um=float(pitch_abs_err),
        depth_abs_err_um=float(depth_abs_err),
        angle_err_deg=float(angle_err),
        pitch_pass=pitch_pass,
        depth_pass=depth_pass,
        angle_pass=angle_pass,
        error="",
    )


# =============================================================================
# Summary and reporting
# =============================================================================


def _stat(values: List[float]) -> Dict[str, float]:
    # Compute mean, std, max of a list of errors
    a = np.asarray(values, dtype=float)
    a = a[np.isfinite(a)]
    if a.size == 0:
        return {"mean": float("nan"), "std": float("nan"), "max": float("nan")}
    return {
        "mean": float(np.mean(a)),
        "std": float(np.std(a, ddof=1)) if a.size > 1 else 0.0,
        "max": float(np.max(a)),
    }


def _summarize(
    results: List[VerificationResult], cfg: ValidationConfig
) -> Dict[str, Any]:
    # Summarize validation results
    total = len(results)
    passed = sum(1 for r in results if r.passed)
    errors = sum(1 for r in results if bool(r.error))
    valid = [r for r in results if not r.error]

    def col(attr: str) -> List[float]:
        return [float(getattr(r, attr)) for r in valid]

    # Group by pitch/depth combination
    combos: Dict[str, Dict[str, Any]] = {}
    for r in results:
        key = f"p{r.pitch_truth_um:.0f}_d{r.depth_truth_um:.0f}"
        if key not in combos:
            combos[key] = {"total": 0, "passed": 0}
        combos[key]["total"] += 1
        if r.passed:
            combos[key]["passed"] += 1

    for key in combos:
        t = combos[key]["total"]
        p = combos[key]["passed"]
        combos[key]["pass_rate"] = (p / t) if t else 0.0

    return {
        "total_samples": total,
        "passed": passed,
        "failed": total - passed,
        "errors": errors,
        "overall_pass_rate": (passed / total) if total else 0.0,
        "pitch_mape": _stat(col("pitch_mape_pct")),
        "depth_mape": _stat(col("depth_mape_pct")),
        "pitch_abs_err_um": _stat(col("pitch_abs_err_um")),
        "depth_abs_err_um": _stat(col("depth_abs_err_um")),
        "angle_err_deg": _stat(col("angle_err_deg")),
        "combo_breakdown": combos,
        "thresholds": asdict(cfg),
    }


def _write_report(
    dataset_dir: Path, summary: Dict[str, Any], results: List[VerificationResult]
) -> Path:
    # Write a markdown validation report
    report = dataset_dir / "VALIDATION_REPORT.md"
    failed = [r for r in results if not r.passed]
    th = summary["thresholds"]

    with open(report, "w", encoding="utf-8") as f:
        f.write("# Holographic Groove Analyzer Validation Report\n\n")
        f.write(f"**Generated:** {summary.get('timestamp', '')}\n\n")
        f.write(f"**Analyzer:** {summary.get('analyzer', '')}\n\n")

        f.write("## Executive Summary\n\n")
        f.write(f"- Total samples: {summary['total_samples']}\n")
        f.write(f"- Passed: {summary['passed']} ({summary['overall_pass_rate']:.1%})\n")
        f.write(f"- Failed: {summary['failed']}\n")
        f.write(f"- Analyzer errors: {summary['errors']}\n\n")

        f.write("## Acceptance Criteria\n\n")
        f.write("| Metric | Threshold |\n|---|---:|\n")
        f.write(f"| Pitch MAPE | ≤ {th['pitch_mape_thresh_pct']}% |\n")
        f.write(f"| Depth MAPE | ≤ {th['depth_mape_thresh_pct']}% |\n")
        f.write(f"| Angle error | ≤ {th['angle_err_thresh_deg']}° |\n\n")

        f.write("## Error Statistics\n\n")
        f.write("| Metric | Mean | Std | Max |\n|---|---:|---:|---:|\n")

        def _fmt_stat(s: Dict[str, float], unit: str = "") -> str:
            return (
                f"{s['mean']:.2f}{unit} | {s['std']:.2f}{unit} | {s['max']:.2f}{unit}"
            )

        f.write(f"| Pitch MAPE | {_fmt_stat(summary['pitch_mape'], '%')} |\n")
        f.write(
            f"| Pitch |abs err| | {_fmt_stat(summary['pitch_abs_err_um'], ' µm')} |\n"
        )
        f.write(f"| Depth MAPE | {_fmt_stat(summary['depth_mape'], '%')} |\n")
        f.write(
            f"| Depth |abs err| | {_fmt_stat(summary['depth_abs_err_um'], ' µm')} |\n"
        )
        f.write(f"| Angle error | {_fmt_stat(summary['angle_err_deg'], '°')} |\n\n")

        f.write("## Results by Pitch/Depth Combination\n\n")
        f.write("| Combination | Total | Passed | Pass Rate |\n|---|---:|---:|---:|\n")
        for key in sorted(summary.get("combo_breakdown", {}).keys()):
            cb = summary["combo_breakdown"][key]
            f.write(
                f"| {key} | {cb['total']} | {cb['passed']} | {cb['pass_rate']:.1%} |\n"
            )
        f.write("\n")

        f.write("## Failed Samples (first 25)\n\n")
        if not failed:
            f.write("No failed samples. ✓\n")
        else:
            f.write("| File | Pitch MAPE | Depth MAPE | Angle err | Reason |\n")
            f.write("|---|---:|---:|---:|---|\n")
            for r in failed[:25]:
                reason = (r.error or "threshold exceeded").replace("\n", " ")[:60]
                f.write(
                    f"| {r.file_name} | {r.pitch_mape_pct:.2f}% | "
                    f"{r.depth_mape_pct:.2f}% | {r.angle_err_deg:.2f}° | {reason} |\n"
                )

    return report


def _log_summary(summary: Dict[str, Any]) -> None:
    # Log a summary of validation results
    LOG.info("=" * 60)
    LOG.info("HOLOGRAPHIC GROOVE VALIDATION SUMMARY")
    LOG.info("=" * 60)
    LOG.info("Analyzer: %s", summary.get("analyzer", ""))
    LOG.info("Total samples: %d", summary.get("total_samples", 0))
    LOG.info(
        "Passed: %d (%.1f%%)",
        summary.get("passed", 0),
        100.0 * float(summary.get("overall_pass_rate", 0.0)),
    )
    LOG.info("Failed: %d", summary.get("failed", 0))
    LOG.info("Errors: %d", summary.get("errors", 0))
    LOG.info("-" * 60)

    def _s(key: str) -> Dict[str, float]:
        s = summary.get(key, {})
        return {
            "mean": float(s.get("mean", float("nan"))),
            "std": float(s.get("std", float("nan"))),
            "max": float(s.get("max", float("nan"))),
        }

    pitch_mape = _s("pitch_mape")
    depth_mape = _s("depth_mape")
    pitch_abs = _s("pitch_abs_err_um")
    depth_abs = _s("depth_abs_err_um")
    angle_err = _s("angle_err_deg")

    LOG.info(
        "Pitch MAPE: %.2f%% ± %.2f%% (max: %.2f%%)",
        pitch_mape["mean"],
        pitch_mape["std"],
        pitch_mape["max"],
    )
    LOG.info(
        "Pitch |abs err|: %.3f ± %.3f µm (max: %.3f µm)",
        pitch_abs["mean"],
        pitch_abs["std"],
        pitch_abs["max"],
    )
    LOG.info(
        "Depth MAPE: %.2f%% ± %.2f%% (max: %.2f%%)",
        depth_mape["mean"],
        depth_mape["std"],
        depth_mape["max"],
    )
    LOG.info(
        "Depth |abs err|: %.3f ± %.3f µm (max: %.3f µm)",
        depth_abs["mean"],
        depth_abs["std"],
        depth_abs["max"],
    )
    LOG.info(
        "Angle error: %.2f° ± %.2f° (max: %.2f°)",
        angle_err["mean"],
        angle_err["std"],
        angle_err["max"],
    )
    LOG.info("-" * 60)

    LOG.info("Per-combination pass rates:")
    cb = summary.get("combo_breakdown", {}) or {}
    for name in sorted(cb.keys()):
        st = cb.get(name, {}) or {}
        total = int(st.get("total", 0))
        passed = int(st.get("passed", 0))
        rate = 100.0 * float(st.get("pass_rate", 0.0)) if total else 0.0
        LOG.info("  %s: %d/%d (%.1f%%)", name, passed, total, rate)

    LOG.info("=" * 60)
    report_path = summary.get("report_path")
    if report_path:
        LOG.info("Validation report written to: %s", report_path)


# =============================================================================
# Main validation runner
# =============================================================================


def run_validation(
    dataset_dir: Path, analyzer_path: Path
) -> Tuple[List[VerificationResult], Dict[str, Any]]:
    # Run validation on a synthetic dataset
    dataset_dir = dataset_dir.resolve()
    if not dataset_dir.is_dir():
        raise NotADirectoryError(f"Dataset directory does not exist: {dataset_dir}")

    truth = dataset_dir / "truth_index.csv"
    if not truth.exists():
        raise FileNotFoundError(f"Could not find truth_index.csv in {dataset_dir}")

    samples = _read_truth_index(truth)
    if not samples:
        raise RuntimeError("truth_index.csv contained 0 samples.")

    mod, label, api_version = _load_analyzer_module(analyzer_path)

    cfg = ValidationConfig()

    out_root = dataset_dir / "analysis_outputs"
    out_root.mkdir(parents=True, exist_ok=True)

    LOG.info("Running holographic validation with analyzer: %s", label)
    LOG.info("Dataset: %s (%d samples)", dataset_dir, len(samples))

    results: List[VerificationResult] = []
    for i, s in enumerate(samples, 1):
        results.append(_verify_one(mod, s, cfg, out_root, api_version))
        if i % 10 == 0 or i == len(samples):
            n_pass = sum(1 for x in results if x.passed)
            LOG.info("Verified %d/%d samples (%d passed)", i, len(samples), n_pass)

    summary = _summarize(results, cfg)
    summary["analyzer"] = label
    summary["timestamp"] = time.strftime("%Y-%m-%d %H:%M:%S")

    _write_csv(dataset_dir / "verification_results.csv", [asdict(r) for r in results])
    with open(dataset_dir / "verification_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    report = _write_report(dataset_dir, summary, results)
    summary["report_path"] = str(report.resolve())

    _log_summary(summary)
    return results, summary


# =============================================================================
# CLI and GUI entry points
# =============================================================================


def _setup_logging(level: str) -> None:
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[logging.StreamHandler(sys.stdout)],
    )


def main_gui() -> None:
    _setup_logging("INFO")
    _gui_info(
        "Holographic Groove Validation",
        "You will be asked to:\n"
        "1) Select the analyzer (.py)\n"
        "2) Select the dataset folder (must contain truth_index.csv)\n",
    )
    analyzer = _gui_pick_file("Select holographic analyzer (.py)")
    ds = _gui_pick_dir("Select dataset folder (containing truth_index.csv)")
    try:
        run_validation(ds, analyzer)
        _gui_info(
            "Validation Complete", "See VALIDATION_REPORT.md in the dataset folder."
        )
    except Exception as e:
        _gui_info("Validation error", str(e), kind="error")


def main_cli(dataset_dir: str, analyzer_path: str, *, log_level: str) -> None:
    _setup_logging(log_level)
    try:
        run_validation(Path(dataset_dir), Path(analyzer_path))
    except Exception:
        LOG.exception("Validation failed")
        raise SystemExit(1)


if __name__ == "__main__":
    p = argparse.ArgumentParser(
        description="Validate a holographic groove analyzer against a synthetic dataset",
        epilog=f"Example: python {Path(__file__).name} -a groove_analyzer_holo.py -d ./synthetic_dataset",
    )
    p.add_argument("--gui", action="store_true", help="Use GUI dialogs")
    p.add_argument("-a", "--analyzer-path", type=str, help="Path to analyzer (.py)")
    p.add_argument(
        "-d",
        "--dataset-dir",
        type=str,
        help="Dataset directory containing truth_index.csv",
    )
    p.add_argument(
        "--log", type=str, default="INFO", help="Logging level (INFO, WARNING, ERROR)"
    )
    args = p.parse_args()

    if args.gui:
        main_gui()
    else:
        if not args.analyzer_path or not args.dataset_dir:
            raise SystemExit(
                "Must specify --analyzer-path and --dataset-dir (or use --gui)"
            )
        main_cli(args.dataset_dir, args.analyzer_path, log_level=args.log)
